### ISSUE TITLE
US - Sort Tasks List

### ISSUE THREAD

**Issue by nastiche** [nastiche/capstone_taskifai_app#14]
## Value Proposition

**As a** user

**I want to be able to** sort my tasks in the tasks list

**so that I can** have a better overview of what needs to be done.
​

## Description

![us8](https://github.com/nastiche/taskifai/assets/97537490/796708dc-96e7-4ef2-99bb-922a5b55a7b7)

## Acceptance Criteria

- [ ] On the `TasksListPage` button `sort` is displayed
- [ ] Clicking on `sort` button makes dropdown container with sort options visible
- [ ] Clicking on one of the dropdown options sorts the tasks list accordingly to the chosen option
- [ ] Clicking on one of the dropdown options makes dropdown container hidden

## Tasks

- [ ] Create `SortDropdown` component
- [ ] Implement `SortDropdown` component in the `TasksListPage`

**Comment by actyvystom** [comment]
A nice one! 👍🏻 
Anyway, one question came up in my head concerning your acceptance criteria: if choosing one of the sorting options deactivates the dropdown, how can the user choose another option for sorting when he wants to see another sorting? 🤔

**Comment by nastiche** [comment]
The user should click again on the sort button which activates the dropdown list

**Comment by actyvystom** [comment]
> The user should click again on the sort button which activates the dropdown list

Then you should better describe it like e.g. the dropdown container gets _hidden_ (and that another click on the sort button displays it again). Deactivating implies that its set to be disabled.

**Comment by nastiche** [comment]
ok, cool, will do, tnx!
