### ISSUE TITLE
US - Image Upload

### ISSUE THREAD

**Issue by nastiche** [nastiche/capstone_taskifai_app#20]
## Value Proposition

**As a** user

**I want to be able to** upload an image and attach it to my task

**so that I can** have a better overview of task details.
​

## Description

![us9](https://github.com/nastiche/capstone_taskifai_app/assets/97537490/5d5c586a-f6ea-4736-9138-c4aa8c783726)

## Acceptance Criteria

- [ ] On the `CreateTaskPage` button `choose file` is displayed
- [ ] Clicking on the `choose file` button makes a window appear where user can choose a file from the local directory
- [ ] Clicking on `create` button (task input form submit) makes image be displayed on the `TaskDetailsPage` 

## Tasks

- [ ] Create new branch `image-upload`
- [ ] Create `choose file` button with corresponding function
- [ ] Implement `cloudinary` upload function
- [ ] Add image display to the `TaskDetails` component

**Comment by JonasDaJones** [comment]
I like that story, just have one issue. The window for upload (Acceptance, 2) is not shown in the description scribble, that does not bother me, but I have no Idea, where this is part of your tasks. As for now, after you have finished your tasks, I will find a button, an image will be uploaded to cloudinary and displayed in the TaskDetails. But where and when do I add the image? Cheers, J.

**Comment by nastiche** [comment]
Good point, I though about it too, but I didn't know how it will look like, I will just make it like in the demo. But I will try to make a scribble first ))))

**Comment by nastiche** [comment]
I added a `choose file` button. After you click on it local window to your directory shows up (you don't have to code it yourself, so you don't have to show it on the scribble) and you choose one of your local files. Then you click on `upload` button in the app itself.

**Comment by nastiche** [comment]
Refactoring: only `choose file` button is displayed. Upload happens on task input form submit.

**Comment by sebastianwel** [comment]
lgtm now 😁
