### ISSUE TITLE
US - Buttons Styling

### ISSUE THREAD

**Issue by nastiche** [nastiche/capstone_taskifai_app#23]
## Value Proposition

**As a** user

**I want to ** have clearly designed buttons

**so that I can** intuitively navigate through the app.
​

## Description

![Image](https://github.com/nastiche/capstone_taskifai_app/assets/97537490/008f88c3-db79-4596-9df3-5fd0be94d9d7)

## Acceptance Criteria

- [ ] On the `TasksListPage` button `+` is displayed
- [ ] Clicking on the `+` button brings the user to the `CreateTaskPage`
- [ ] On the `CreateTaskPage` `❌`, `✅`, `🔄` buttons are displayed
- [ ] Clicking on `❌` button brings the user back to the `TasksListPage`
- [ ] Clicking on `✅` button creates the task and brings the user back to the `TasksListPage` where the newly created task is displayed
- [ ] Clicking on `🔄` button resets the input form

## Tasks

- [ ] Create new branch `buttons-styling`
- [ ] Create `❌`, `✅`, `🔄` buttons with the corresponding functions
