### ISSUE TITLE
US - Buttons Styling

### ISSUE THREAD

**Issue by nastiche** [nastiche/capstone_taskifai_app#24]
## Value Proposition

**As a** user

**I want to** have clearly designed buttons

**so that I can** intuitively navigate through the app.
​

## Description

![us_10](https://github.com/nastiche/capstone_taskifai_app/assets/97537490/0488be34-64bf-4869-ba9b-b1111c61d95b)

- [ ] On the `TasksListPage` button `+` is displayed
- [ ] Clicking on `+` brings the user to the `CreateTaskPage`
- [ ] On the `CreateTaskPage` `✅`, `🔄` buttons and `🏠`, `❌` links are displayed
- [ ] Clicking on `❌` link brings the user back to the `TasksListPage`
- [ ] Clicking on `✅` button creates the task and brings the user back to the `TasksListPage` where the newly created task is displayed
- [ ] Clicking on `🔄` button resets the input form
- [ ] Clicking on the `🏠` link brings the user to the `TasksListPage`
- [ ] On the `TaskDetailsPage` `🗑️`, `🔧`, `🔗` buttons and a `🏠` link are displayed
- [ ] Clicking on `🗑️` deletes the task and brings user back to the `TasksListPage`
- [ ] Clicking on `🔧` brings the user to the `EditTaskPage`
- [ ] Clicking on `🔗` copies the URL of the task to Clipboard
- [ ] On the `EditTaskPage` `✅`, `🔄` buttons and `🏠`, `❌` links are displayed
- [ ] Clicking on `❌` link brings the user back to the `TasksListPage`
- [ ] Clicking on `✅` button creates the task and brings the user back to the `TasksListPage` where the newly edited task is displayed
- [ ] Clicking on `🔄` button resets the input form
- [ ] Clicking on the `🏠` link brings the user to the `TasksListPage`

## Tasks

- [ ] Create new branch `buttons-styling`
- [ ] Create `✅`, `🔄`, `🗑️`, `🔧`, `🔗` buttons and `❌`, `🏠` links with the corresponding functions

**Comment by rueveydaakuel** [comment]
Very detailed user story, I like it 🥳

**Comment by JonasDaJones** [comment]
+ button works perfect
✅ says task created, but keeps me on the create task page
reset works fine
home leads me back to task list
edit works
delete works

yeah, cool one, ony the routing after task created is different to US.
cheers

**Comment by nastiche** [comment]
Yeah, I am still not sure what is best for the user. What do you think. Should the user stay on the create page or go back to tasks list?

**Comment by JonasDaJones** [comment]
no easy decision. When I'm really motivated and create task after task, i'd like the current version.
When i'm tired and insecure, i would want to check if task really was created (even if the popup told me).
