### ISSUE TITLE
US - Task Card Styling

### ISSUE THREAD

**Issue by nastiche** [nastiche/capstone_taskifai_app#26]
## Value Proposition

**As a** user

**I want to** have an easy access to the task details

**so that I** spend as less time as possible on navigation in the app 
​

## Description

![task-card](https://github.com/nastiche/capstone_taskifai_app/assets/97537490/f657f4f9-bef1-48e5-9dc2-bdb4e27eeff4)

- [ ] On the `TasksListPage` on every `TaskCard` `🔽` button is displayed
- [ ] Clicking on the button makes the `TaskCard` expand to the `TaskDetailsCard`
- [ ] On the `TaskDetailsCard` `🔽`,`🗑️` buttons and a `🔧` link are displayed
- [ ] Clicking on `🗑️` button deletes the task and `TaskDetailsCard` disappears from the `TasksListPage`
- [ ] Clicking on `🔧` link brings user to the `EditTaskPage`
- [ ] Clicking on `🔼` button makes `TaskDetailsCard` shrink to the `TaskCard`

## Tasks

- [ ] Create new branch `task-card-styling`
- [ ] Delete `TaskDetailsPage`
- [ ] Create `TaskDetailsCard` component
- [ ] Create `🔽`, `🔼`, `🗑️` buttons and a `🔧` link with the corresponding functions

**Comment by JonasDaJones** [comment]
Easy to understand. Very clear and detailed US.
