### ISSUE TITLE
US - Input Form Styling

### ISSUE THREAD

**Issue by nastiche** [nastiche/capstone_taskifai_app#28]
## Value Proposition

**As a** user

**I want to** have an intuitive input form

**so that I** spend as less time as possible on creating new and editing existing tasks
​

## Description

![us_12](https://github.com/nastiche/capstone_taskifai_app/assets/97537490/ac668a23-be55-4951-9556-46a71f0483f1)

- [ ] On the `CreateTaskPage` the input forms in regular and AI mode look fabulous and provide superb user experience
- [ ] On the `EditTaskPage` the input form looks fabulous and provides superb user experience

## Tasks

- [ ] Create new branch `input-form-styling`
- [ ] Add styling to `RegularTaskInputForm` and `AiTaskInputForm`

**Comment by MichanNan** [comment]
LGTM 🚀
