### ISSUE TITLE
US - Finish Styling

### ISSUE THREAD

**Issue by nastiche** [nastiche/capstone_taskifai_app#30]
## Value Proposition

**As a** user

**I want to** have a smooth UI experience

**so that I** can enjoy every second spent in the taskifAI app.
​

## Description

There are animations running every time user waits for page response. Clicking on links and buttons results in visual effects.

##Acceptance Criteria
- [ ] Every time page is loading animation is being displayed on the page.
- [ ] Clicking on buttons and links results in visual effects.

## Tasks

- [ ] Create new branch `finish-styling`
- [ ] Create animations and click effects
